### ISSUE TITLE
Don't work (huh?)

### ISSUE THREAD

**Issue by Noneatme** [dutchcoders/extract-riff#1]
I'm getting this error:

Exporting wav to /tmp/lego/bla1/JUKEBOX.SI\0_MusicTheme1.wav
Traceback (most recent call last):
  File "./test.py", line 207, in <module>
    extract(args.paths, args.output)
  File "./test.py", line 86, in extract
    w = wave.open(os.path.join(dest, os.path.basename(filename), "{0}_{1}.wav".f
ormat(str(mxob.id), os.path.basename(mxob.s3))), 'wb')
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 499, in open
    return Wave_write(f)
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 293, in __init__
    f = builtins.open(f, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lego/bla1/JUKEBOX.
SI\0_MusicTheme1.wav'
Exception ignored in: <bound method Wave_write.__del__ of <wave.Wave_write objec
t at 0x02DEA330>>
Traceback (most recent call last):
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 315, in **del**
    self.close()
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 431, in close
    if self._file:
AttributeError: 'Wave_write' object has no attribute '_file'

Command used:

python ./test.py --extract --output "/tmp/lego/bla1/" "JUKEBOX.SI"

**Comment by nl5887** [comment]
Are you sure the folder /tmp/lego/bla1/ exists? I see you are using Windows. Try this:

python ./test.py --extract --output "c:\temp\" "JUKEBOX.SI".

And make sure the c:\temp folder exists.

**Comment by Noneatme** [comment]
F:\Programme (32 Bit)\Phyton>python ./test.py --extract --output "c:\temp\" "JUK
EBOX.SI"
usage: test.py [-h] [-v] [--extract] [--output OUTPUT] [--dump]
               paths [paths ...]
test.py: error: the following arguments are required: paths

**Comment by nl5887** [comment]
Sorry, my mistake the \" escapes the ". Try this:

python ./test.py --extract --output c:\temp\ "JUKEBOX.SI"

**Comment by Noneatme** [comment]
Now this:

Exporting wav to c:\temp\JUKEBOX.SI\0_MusicTheme1.wav
Traceback (most recent call last):
  File "./test.py", line 207, in <module>
    extract(args.paths, args.output)
  File "./test.py", line 92, in extract
    w.writeframesraw(x.data[14:])
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 415, in writeframesraw
    self._ensure_header_written(len(data))
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 455, in _ensure_header_w
ritten
    self._write_header(datasize)
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 472, in _write_header
    self._sampwidth \* 8, b'data'))
struct.error: required argument is not an integer
Exception ignored in: <bound method Wave_write.__del__ of <wave.Wave_write objec
t at 0x027FA330>>
Traceback (most recent call last):
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 315, in **del**
    self.close()
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 433, in close
    self._ensure_header_written(0)
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 455, in _ensure_header_w
ritten
    self._write_header(datasize)
  File "F:\Programme (32 Bit)\Phyton\lib\wave.py", line 472, in _write_header
    self._sampwidth \* 8, b'data'))
struct.error: required argument is not an integer

Maybe I use the wrong python version?

**Comment by nl5887** [comment]
Yes, that could be, or something because it isn't tested on windows. What version of Python are you using? I've tested it on 2.7.

**Comment by Noneatme** [comment]
Yep, 2.7 works. Thanks!

I have the german lego island sound files, I will try to extract them

**Comment by nl5887** [comment]
Great, succes. Let me know if you've got other things.

**Comment by Noneatme** [comment]
ISLE.SI don't work

Traceback (most recent call last):
  File "./test.py", line 207, in <module>
    extract(args.paths, args.output)
  File "./test.py", line 47, in extract
    for subchunk in subchunk_iter:
  File "F:\Programme (32 Bit)\Python278\lego_extract__init__.py", line 74, in s
ubchunks
    for x in p.subchunks():
  File "F:\Programme (32 Bit)\Python278\lego_extract__init__.py", line 113, in
subchunks
    for x in iter_subchunks:
  File "F:\Programme (32 Bit)\Python278\lego_extract__init__.py", line 74, in s
ubchunks
    for x in p.subchunks():
  File "F:\Programme (32 Bit)\Python278\lego_extract__init__.py", line 63, in s
ubchunks
    logger.debug ("{0} {1} {2}".format(subchunk.signature, subchunk.block_size,
binascii.hexlify(subchunk.data[:50])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 1: ordinal
not in range(128)

I will try the other ones

/edit: They all return this error ._.

/Edit: Ok the error occurs only on some files

**Comment by Noneatme** [comment]
OK I managed to extract all files, except ISLE.SI and ACT2MAIN.SI

**Comment by ghost** [comment]
i cannot extract audio in python 3.9 about the same errors that the author described. images and smk videos seem to work, but i got the 1_CDSpin1_Smk.unknown from NOCD.SI for some reason with that extension. But it otherwise seems to work without audio at least in VLC.


C:\Program Files (x86)\LEGO Island>python ./test.py --extract --output c:\temp\ "C:\Program Files (x86)\LEGO Island\lego\Scripts\NOCD.SI"
Extracting C:\Program Files (x86)\LEGO Island\lego\Scripts\NOCD.SI.
b'020002000000010010000000'
b'4d784864'
b'MxHd' 12 b'020002000000010010000000'
        Chunk b'MxHd': Block size: 12 -> b'\x02\x00\x02\x00\x00\x00\x01\x00\x10\x00\x00\x00'
b'030000003c000000'
b'4d784f66'
b'MxOf' 8 b'030000003c000000'
        Chunk b'MxOf': Block size: 8 -> b'\x03\x00\x00\x00<\x00\x00\x00'
b'4d7853744d7853746c6505004d784f62f2010000070000000000004e6f43445f4d6f76696500000000002200000000000000'
b'4c495354'
b'LIST' 393160 b'4d7853744d7853746c6505004d784f62f2010000070000000000004e6f43445f4d6f76696500000000002200000000000000'
        List ('(b'MxSt',)'): 393160
b'4d784f62f2010000070000000000004e6f43445f4d6f76696500000000002200000000000000000000000100000000000000'
b'4d785374'
b'MxSt' 353644 b'4d784f62f2010000070000000000004e6f43445f4d6f76696500000000002200000000000000000000000100000000000000'
                (MxSt Chunk) b'4d784f62f2010000070000000000004e6f43445f4d6f766965000000000022000000000000000000'
b'070000000000004e6f43445f4d6f766965000000000022000000000000000000000001000000000000000000000000000000'
b'4d784f62'
b'MxOb' 498 b'070000000000004e6f43445f4d6f766965000000000022000000000000000000000001000000000000000000000000000000'
7
                        (MxOb Chunk) 'b'MxOb'' 498 id: 0 7  NoCD_Movie None None
b'4d784368020000004d784f62aa0000000300000000000043445370696e315f536d6b00010000002200000000000000480d00'
b'4c495354'
b'LIST' 378 b'4d784368020000004d784f62aa0000000300000000000043445370696e315f536d6b00010000002200000000000000480d00'
                                List ('(b'MxCh',)'): 378
b'0300000000000043445370696e315f536d6b00010000002200000000000000480d0000010000000000000000000000000000'
b'4d784f62'
b'MxOb' 170 b'0300000000000043445370696e315f536d6b00010000002200000000000000480d0000010000000000000000000000000000'
3
                                        (MxOb Chunk) 'b'MxOb'' 170 id: 1 3  CDSpin1_Smk q:\lego\media\movies\CDSpin1.smk
b'04000000000000496963783632496e5f5761766500020000002200000000000000570d000001000000000000000000000000'
b'4d784f62'
b'MxOb' 183 b'04000000000000496963783632496e5f5761766500020000002200000000000000570d000001000000000000000000000000'
4
                                        (MxOb Chunk) 'b'MxOb'' 183 id: 2 4  Iicx62In_Wave WAV☺ q:\lego\Audio\Offscreen\In\Iicx62In.wav
b'4d7844614d7843680e6a0000000001000000ffffffff006a0000534d4b3240010000f000000022000000f0d8ffff00000000'
b'4c495354'
b'LIST' 353130 b'4d7844614d7843680e6a0000000001000000ffffffff006a0000534d4b3240010000f000000022000000f0d8ffff00000000'
                        List ('(b'MxDa',)'): 353130
b'000001000000ffffffff006a0000534d4b3240010000f000000022000000f0d8ffff00000000000000000000000000000000'
b'4d784368'
b'MxCh' 27150 b'000001000000ffffffff006a0000534d4b3240010000f000000022000000f0d8ffff00000000000000000000000000000000'
                                (MxCh Chunk) Parent: None b'MxCh' 27150 id: 1 mode: 0 b'4b3240010000f000000022000000f0d8ffff00000000000000000000000000000000'
b'000002000000ffffffff1800000001000100112b00002256000002001000322601002c000000'
b'4d784368'
b'MxCh' 38 b'000002000000ffffffff1800000001000100112b00002256000002001000322601002c000000'
                                (MxCh Chunk) Parent: None b'MxCh' 38 id: 2 mode: 0 b'0100112b00002256000002001000322601002c000000'
b'00000100000000000000e0270000b18a170000011916000b002828281814002a12130c0b002a17010500003333330015001f'
b'4d784368'
b'MxCh' 10222 b'00000100000000000000e0270000b18a170000011916000b002828281814002a12130c0b002a17010500003333330015001f'
                                (MxCh Chunk) Parent: None b'MxCh' 10222 id: 1 mode: 0 b'170000011916000b002828281814002a12130c0b002a17010500003333330015001f'
b'0000020000000000000022560000000007001800200023002a002c0033002f001e001500120014001100100014001f002800'
b'4d784368'
b'MxCh' 22064 b'0000020000000000000022560000000007001800200023002a002c0033002f001e001500120014001100100014001f002800'
                                (MxCh Chunk) Parent: None b'MxCh' 22064 id: 2 mode: 0 b'07001800200023002a002c0033002f001e001500120014001100100014001f002800'
b'cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd'
b'70616420'
b'pad ' 5436 b'cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd'
Skipping padding
b'0000010000006400000064250000ec12c3d719004071a47e00a43aa0d80e00bf75becf5632008c1c56989b0160a8de01b682'
b'4d784368'
b'MxCh' 9586 b'0000010000006400000064250000ec12c3d719004071a47e00a43aa0d80e00bf75becf5632008c1c56989b0160a8de01b682'
                                (MxCh Chunk) Parent: None b'MxCh' 9586 id: 1 mode: 0 b'c3d719004071a47e00a43aa0d80e00bf75becf5632008c1c56989b0160a8de01b682'
b'000001000000c80000002c210000ec129955d2c10c00602a2b8e07a0eb183553bbcf0c80082da13f0b06405460359f0503c0'
b'4d784368'
b'MxCh' 8506 b'000001000000c80000002c210000ec129955d2c10c00602a2b8e07a0eb183553bbcf0c80082da13f0b06405460359f0503c0'
                                (MxCh Chunk) Parent: None b'MxCh' 8506 id: 1 mode: 0 b'9955d2c10c00602a2b8e07a0eb183553bbcf0c80082da13f0b06405460359f0503c0'
b'0000010000002c0100006c1a0000ec12996d8001d02afad17c39b013759288831ccb707706e997c95a092b5ecb0094b9e9e7'
b'4d784368'
b'MxCh' 6778 b'0000010000002c0100006c1a0000ec12996d8001d02afad17c39b013759288831ccb707706e997c95a092b5ecb0094b9e9e7'
                                (MxCh Chunk) Parent: None b'MxCh' 6778 id: 1 mode: 0 b'996d8001d02afad17c39b013759288831ccb707706e997c95a092b5ecb0094b9e9e7'
b'00000100000090010000dc0c0000ec1267e40b63b28ea6ead483f2796180a52a569a44536a75b2ebe85b834e26d158412e85'
b'4d784368'
b'MxCh' 3306 b'00000100000090010000dc0c0000ec1267e40b63b28ea6ead483f2796180a52a569a44536a75b2ebe85b834e26d158412e85'
                                (MxCh Chunk) Parent: None b'MxCh' 3306 id: 1 mode: 0 b'67e40b63b28ea6ead483f2796180a52a569a44536a75b2ebe85b834e26d158412e85'
b'000001000000f401000054110000ec12275b660000095300c0393dd8042f19cc1cab3dc835c9eb688701f0205d3f1c012e53'
b'4d784368'
b'MxCh' 4450 b'000001000000f401000054110000ec12275b660000095300c0393dd8042f19cc1cab3dc835c9eb688701f0205d3f1c012e53'
                                (MxCh Chunk) Parent: None b'MxCh' 4450 id: 1 mode: 0 b'275b660000095300c0393dd8042f19cc1cab3dc835c9eb688701f0205d3f1c012e53'
b'0000010000005802000024190000ec12271bc0000038470090540edb840350be87bac00080d1bcbdc30c0020d0eb2ae46454'
b'4d784368'
b'MxCh' 6450 b'0000010000005802000024190000ec12271bc0000038470090540edb840350be87bac00080d1bcbdc30c0020d0eb2ae46454'
                                (MxCh Chunk) Parent: None b'MxCh' 6450 id: 1 mode: 0 b'271bc0000038470090540edb840350be87bac00080d1bcbdc30c0020d0eb2ae46454'
b'000001000000bc020000f41d0000ec12275b6600005ec63d00c0a2667300002f873e00405c2ff7c4850f00e095921e2a883e'
b'4d784368'
b'MxCh' 7682 b'000001000000bc020000f41d0000ec12275b6600005ec63d00c0a2667300002f873e00405c2ff7c4850f00e095921e2a883e'
                                (MxCh Chunk) Parent: None b'MxCh' 7682 id: 1 mode: 0 b'275b6600005ec63d00c0a2667300002f873e00405c2ff7c4850f00e095921e2a883e'
b'00000100000020030000e0200000ec1227da18008097714b1ddc0f00f03a2f0f00507e313a711b953c0079ac32edf4431e57'
b'4d784368'
b'MxCh' 8430 b'00000100000020030000e0200000ec1227da18008097714b1ddc0f00f03a2f0f00507e313a711b953c0079ac32edf4431e57'
                                (MxCh Chunk) Parent: None b'MxCh' 8430 id: 1 mode: 0 b'27da18008097714b1ddc0f00f03a2f0f00507e313a711b953c0079ac32edf4431e57'
b'00000100000084030000e8220000ec12c32f99020c0080b478b307002804b9e603003ce2850300d832ee00008bb16d3a71e3'
b'4d784368'
b'MxCh' 8950 b'00000100000084030000e8220000ec12c32f99020c0080b478b307002804b9e603003ce2850300d832ee00008bb16d3a71e3'
                                (MxCh Chunk) Parent: None b'MxCh' 8950 id: 1 mode: 0 b'c32f99020c0080b478b307002804b9e603003ce2850300d832ee00008bb16d3a71e3'
b'cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd'
b'70616420'
b'pad ' 1318 b'cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd'
Skipping padding
b'000001000000e8030000781f0000ec1299e90c00200b0b0000ce110000e6fc3207c0cbb84b28130320ae531beecb00408b47'
b'4d784368'
b'MxCh' 8070 b'000001000000e8030000781f0000ec1299e90c00200b0b0000ce110000e6fc3207c0cbb84b28130320ae531beecb00408b47'
                                (MxCh Chunk) Parent: None b'MxCh' 8070 id: 1 mode: 0 b'99e90c00200b0b0000ce110000e6fc3207c0cbb84b28130320ae531beecb00408b47'
b'000002000000e80300002256000052b3ebad7bacffb273bd55c7c2df6cf8120ceb22a4314842c43d40404a380e2c2a25e514'
b'4d784368'
b'MxCh' 22064 b'000002000000e80300002256000052b3ebad7bacffb273bd55c7c2df6cf8120ceb22a4314842c43d40404a380e2c2a25e514'
                                (MxCh Chunk) Parent: None b'MxCh' 22064 id: 2 mode: 0 b'ebad7bacffb273bd55c7c2df6cf8120ceb22a4314842c43d40404a380e2c2a25e514'
b'0000010000004c0400008c170000ec12996d8001406b3578341e3a3f3a8110fdaa3e923863b03529c2b647fa968901caef54'
b'4d784368'
b'MxCh' 6042 b'0000010000004c0400008c170000ec12996d8001406b3578341e3a3f3a8110fdaa3e923863b03529c2b647fa968901caef54'
                                (MxCh Chunk) Parent: None b'MxCh' 6042 id: 1 mode: 0 b'996d8001406b3578341e3a3f3a8110fdaa3e923863b03529c2b647fa968901caef54'
b'000001000000b0040000ec0c0000ec1267e40b63cc243d45bd21d2c8000fca1d4b536af5e9b5311379eaa1c57ca1d4ca0b93'
b'4d784368'
b'MxCh' 3322 b'000001000000b0040000ec0c0000ec1267e40b63cc243d45bd21d2c8000fca1d4b536af5e9b5311379eaa1c57ca1d4ca0b93'
                                (MxCh Chunk) Parent: None b'MxCh' 3322 id: 1 mode: 0 b'67e40b63cc243d45bd21d2c8000fca1d4b536af5e9b5311379eaa1c57ca1d4ca0b93'
b'00000100000014050000fc140000ec12275b660044577114b0306dca4e9f751d06fb63bdaa1f71181b0c80125c1089901aa7'
b'4d784368'
b'MxCh' 5386 b'00000100000014050000fc140000ec12275b660044577114b0306dca4e9f751d06fb63bdaa1f71181b0c80125c1089901aa7'
                                (MxCh Chunk) Parent: None b'MxCh' 5386 id: 1 mode: 0 b'275b660044577114b0306dca4e9f751d06fb63bdaa1f71181b0c80125c1089901aa7'
b'00000100000078050000a41d0000ec12271bc000a0ae1f829d0e401fa19297bece00d834d1265a9e1900149d7e2f65bc0c00'
b'4d784368'
b'MxCh' 7602 b'00000100000078050000a41d0000ec12271bc000a0ae1f829d0e401fa19297bece00d834d1265a9e1900149d7e2f65bc0c00'
                                (MxCh Chunk) Parent: None b'MxCh' 7602 id: 1 mode: 0 b'271bc000a0ae1f829d0e401fa19297bece00d834d1265a9e1900149d7e2f65bc0c00'
b'000001000000dc050000f4210000ec12271a6600009925ab7a008089f6431c002e59d53a000360615cd601180008e44cb90f'
b'4d784368'
b'MxCh' 8706 b'000001000000dc050000f4210000ec12271a6600009925ab7a008089f6431c002e59d53a000360615cd601180008e44cb90f'
                                (MxCh Chunk) Parent: None b'MxCh' 8706 id: 1 mode: 0 b'271a6600009925ab7a008089f6431c002e59d53a000360615cd601180008e44cb90f'
b'640376246a0fdce4cf8e6171e546adfcc1305ea0bcd5eb0c805a28ce166464e9280b7ae1d4a74303e9488f24714c9f821ee9'
b'70616420'
b'pad ' 4280 b'640376246a0fdce4cf8e6171e546adfcc1305ea0bcd5eb0c805a28ce166464e9280b7ae1d4a74303e9488f24714c9f821ee9'
Skipping padding
b'0000010000004006000040250000ec1267c9146600005de7bf0f0010a1516c07209043a552070c80f2497f3cebc6000072a7'
b'4d784368'
b'MxCh' 9550 b'0000010000004006000040250000ec1267c9146600005de7bf0f0010a1516c07209043a552070c80f2497f3cebc6000072a7'
                                (MxCh Chunk) Parent: None b'MxCh' 9550 id: 1 mode: 0 b'67c9146600005de7bf0f0010a1516c07209043a552070c80f2497f3cebc6000072a7'
b'000001000000a406000090240000ec12c3d71900003b513f0052780ac576009a75689fad6400f441d156989b0160a8de01de'
b'4d784368'
b'MxCh' 9374 b'000001000000a406000090240000ec12c3d71900003b513f0052780ac576009a75689fad6400f441d156989b0160a8de01de'
                                (MxCh Chunk) Parent: None b'MxCh' 9374 id: 1 mode: 0 b'c3d71900003b513f0052780ac576009a75689fad6400f441d156989b0160a8de01de'
b'0000010000000807000054210000ec129955901b660024d554561c0f401c8c9aa9dd6706409ebf6e6a9f6500d42e27dab360'
b'4d784368'
b'MxCh' 8546 b'0000010000000807000054210000ec129955901b660024d554561c0f401c8c9aa9dd6706409ebf6e6a9f6500d42e27dab360'
                                (MxCh Chunk) Parent: None b'MxCh' 8546 id: 1 mode: 0 b'9955901b660024d554561c0f401c8c9aa9dd6706409ebf6e6a9f6500d42e27dab360'
b'0000010000006c0700007c1b0000ec1299d19229c000d82a8de11b6c9241abd09830aabb3d43030c8c9ca49b95fb1c001860'
b'4d784368'
b'MxCh' 7050 b'0000010000006c0700007c1b0000ec1299d19229c000d82a8de11b6c9241abd09830aabb3d43030c8c9ca49b95fb1c001860'
                                (MxCh Chunk) Parent: None b'MxCh' 7050 id: 1 mode: 0 b'99d19229c000d82a8de11b6c9241abd09830aabb3d43030c8c9ca49b95fb1c001860'
b'000001000000d007000020100000ec12c38f3803800b32816869f45a9049e52562ed4bc574c90040090ad79b832bcf7cee89'
b'4d784368'
b'MxCh' 4142 b'000001000000d007000020100000ec12c38f3803800b32816869f45a9049e52562ed4bc574c90040090ad79b832bcf7cee89'
                                (MxCh Chunk) Parent: None b'MxCh' 4142 id: 1 mode: 0 b'c38f3803800b32816869f45a9049e52562ed4bc574c90040090ad79b832bcf7cee89'
b'000002000000d007000022560000cbf914f4e5f879edc8ef45db92e03adbb3ce13d6c1d3adcc2dc947eae9f6d9b03fe77e17'
b'4d784368'
b'MxCh' 22064 b'000002000000d007000022560000cbf914f4e5f879edc8ef45db92e03adbb3ce13d6c1d3adcc2dc947eae9f6d9b03fe77e17'
                                (MxCh Chunk) Parent: None b'MxCh' 22064 id: 2 mode: 0 b'14f4e5f879edc8ef45db92e03adbb3ce13d6c1d3adcc2dc947eae9f6d9b03fe77e17'
b'00000100000034080000000f0000ec12279a72064052254c01b4565e728eb7af0c033861b5103333c8f0ba5e9653b3f23457'
b'4d784368'
b'MxCh' 3854 b'00000100000034080000000f0000ec12279a72064052254c01b4565e728eb7af0c033861b5103333c8f0ba5e9653b3f23457'
                                (MxCh Chunk) Parent: None b'MxCh' 3854 id: 1 mode: 0 b'279a72064052254c01b4565e728eb7af0c033861b5103333c8f0ba5e9653b3f23457'
b'cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd'
b'70616420'
b'pad ' 892 b'cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd'
Skipping padding
b'00000100000098080000d0130000ec12271bcc000038470010570ec7e200c4852d0e3380a1fa304dd804871900f0d0afce67'
b'4d784368'
b'MxCh' 5086 b'00000100000098080000d0130000ec12271bcc000038470010570ec7e200c4852d0e3380a1fa304dd804871900f0d0afce67'
                                (MxCh Chunk) Parent: None b'MxCh' 5086 id: 1 mode: 0 b'271bcc000038470010570ec7e200c4852d0e3380a1fa304dd804871900f0d0afce67'
b'000001000000fc080000ec190000ec12279b330000cea9700000c7994d7f1e6e0700f072e025483a8380039030459f3be471'
b'4d784368'
b'MxCh' 6650 b'000001000000fc080000ec190000ec12279b330000cea9700000c7994d7f1e6e0700f072e025483a8380039030459f3be471'
                                (MxCh Chunk) Parent: None b'MxCh' 6650 id: 1 mode: 0 b'279b330000cea9700000c7994d7f1e6e0700f072e025483a8380039030459f3be471'
b'000001000000600900000c1a0000ec1227da1900400f0200c04bce2975703b00c0ebbcacc3a01357f20000a1620140a926cc'
b'4d784368'
b'MxCh' 6682 b'000001000000600900000c1a0000ec1227da1900400f0200c04bce2975703b00c0ebbcacc3a01357f20000a1620140a926cc'
                                (MxCh Chunk) Parent: None b'MxCh' 6682 id: 1 mode: 0 b'27da1900400f0200c04bce2975703b00c0ebbcacc3a01357f20000a1620140a926cc'
b'000001000000c4090000701c0000ec12c3ef1ad51900c06696e9007049fdab2d63007868d6e680320058bef73c8b3300b2f0'
b'4d784368'
b'MxCh' 7294 b'000001000000c4090000701c0000ec12c3ef1ad51900c06696e9007049fdab2d63007868d6e680320058bef73c8b3300b2f0'
                                (MxCh Chunk) Parent: None b'MxCh' 7294 id: 1 mode: 0 b'c3ef1ad51900c06696e9007049fdab2d63007868d6e680320058bef73c8b3300b2f0'
b'000001000000280a0000d01c0000ec12c32f510a300080bacce60000e6b0fe0128aff11000c016db0e00d0c2cb3db5f90038'
b'4d784368'
b'MxCh' 7390 b'000001000000280a0000d01c0000ec12c32f510a300080bacce60000e6b0fe0128aff11000c016db0e00d0c2cb3db5f90038'
                                (MxCh Chunk) Parent: None b'MxCh' 7390 id: 1 mode: 0 b'c32f510a300080bacce60000e6b0fe0128aff11000c016db0e00d0c2cb3db5f90038'
b'0000010000008c0a00002c1a0000ec1299954c61068043e2d2ec072002b39491ba0383510ed9b8d9f42d13038076161d100c'
b'4d784368'
b'MxCh' 6714 b'0000010000008c0a00002c1a0000ec1299954c61068043e2d2ec072002b39491ba0383510ed9b8d9f42d13038076161d100c'
                                (MxCh Chunk) Parent: None b'MxCh' 6714 id: 1 mode: 0 b'99954c61068043e2d2ec072002b39491ba0383510ed9b8d9f42d13038076161d100c'
b'000001000000f00a000098140000ec129945994174d5c38d11db1f9946679697c2f10279329a3ae90c40ab8c925f8d37cc00'
b'4d784368'
b'MxCh' 5286 b'000001000000f00a000098140000ec129945994174d5c38d11db1f9946679697c2f10279329a3ae90c40ab8c925f8d37cc00'
                                (MxCh Chunk) Parent: None b'MxCh' 5286 id: 1 mode: 0 b'9945994174d5c38d11db1f9946679697c2f10279329a3ae90c40ab8c925f8d37cc00'
b'000001000000540b0000a40c0000ec1227663b83c6e48b2874619422a80759270775bfa9197966cf907264325726231f57f9'
b'4d784368'
b'MxCh' 3250 b'000001000000540b0000a40c0000ec1227663b83c6e48b2874619422a80759270775bfa9197966cf907264325726231f57f9'
                                (MxCh Chunk) Parent: None b'MxCh' 3250 id: 1 mode: 0 b'27663b83c6e48b2874619422a80759270775bfa9197966cf907264325726231f57f9'
b'000001000000b80b000000170000ec12271bc000a0aecc4600756d1a9337191c832cf0df6f8a83c15924038c4af0d4ac51bc'
b'4d784368'
b'MxCh' 5902 b'000001000000b80b000000170000ec12271bc000a0aecc4600756d1a9337191c832cf0df6f8a83c15924038c4af0d4ac51bc'
                                (MxCh Chunk) Parent: None b'MxCh' 5902 id: 1 mode: 0 b'271bc000a0aecc4600756d1a9337191c832cf0df6f8a83c15924038c4af0d4ac51bc'
b'000002000000b80b0000be23000049059a0528067306a906e206c506c3067c064306d4056005f2045f04cd0321036302b401'
b'4d784368'
b'MxCh' 9164 b'000002000000b80b0000be23000049059a0528067306a906e206c506c3067c064306d4056005f2045f04cd0321036302b401'
                                (MxCh Chunk) Parent: None b'MxCh' 9164 id: 2 mode: 0 b'9a0528067306a906e206c506c3067c064306d4056005f2045f04cd0321036302b401'
b'b49e24b1bc9718b85099632b4699bfcecbb714af10e058fef596e2bf2678cbb929d007bbe9a889cf448a9adb863851b7cc52'
b'70616420'
b'pad ' 2030 b'b49e24b1bc9718b85099632b4699bfcecbb714af10e058fef596e2bf2678cbb929d007bbe9a889cf448a9adb863851b7cc52'
Skipping padding
b'0000010000001c0c0000181e0000ec1227baf214600024d50fc14e07a00f7e5f020320fd126da2e5990140d1acf84ba63b06'
b'4d784368'
b'MxCh' 7718 b'0000010000001c0c0000181e0000ec1227baf214600024d50fc14e07a00f7e5f020320fd126da2e5990140d1acf84ba63b06'
                                (MxCh Chunk) Parent: None b'MxCh' 7718 id: 1 mode: 0 b'27baf214600024d50fc14e07a00f7e5f020320fd126da2e5990140d1acf84ba63b06'
b'000001000000800c000014220000ec12271a6600009925ab7a00803c536c07804b56b50ec00058189775000600023953eec3'
b'4d784368'
b'MxCh' 8738 b'000001000000800c000014220000ec12271a6600009925ab7a00803c536c07804b56b50ec00058189775000600023953eec3'
                                (MxCh Chunk) Parent: None b'MxCh' 8738 id: 1 mode: 0 b'271a6600009925ab7a00803c536c07804b56b50ec00058189775000600023953eec3'
b'000001000000e40c000000250000ec1267c9146600005de7bf0f0010a1516c0720d03f964a1d3000ca27fdf1ac1b0300c89d'
b'4d784368'
b'MxCh' 9486 b'000001000000e40c000000250000ec1267c9146600005de7bf0f0010a1516c0720d03f964a1d3000ca27fdf1ac1b0300c89d'
                                (MxCh Chunk) Parent: None b'MxCh' 9486 id: 1 mode: 0 b'67c9146600005de7bf0f0010a1516c0720d03f964a1d3000ca27fdf1ac1b0300c89d'
b'020001000000480d000000000000'
b'4d784368'
b'MxCh' 14 b'020001000000480d000000000000'
                                (MxCh Chunk) Parent: None b'MxCh' 14 id: 1 mode: 2 b''
b'020002000000570d000000000000'
b'4d784368'
b'MxCh' 14 b'020002000000570d000000000000'
                                (MxCh Chunk) Parent: None b'MxCh' 14 id: 2 mode: 2 b''
b'020000000000570d000000000000'
b'4d784368'
b'MxCh' 14 b'020000000000570d000000000000'
                                (MxCh Chunk) Parent: None b'MxCh' 14 id: 0 mode: 2 b''
b'46fc8a4c8f2fd5e82e3266321daaae0a00404385920500866908b09fd11f0c8336547199fad2d080e1924b894dd3bec5db7c'
b'70616420'
b'pad ' 39496 b'46fc8a4c8f2fd5e82e3266321daaae0a00404385920500866908b09fd11f0c8336547199fad2d080e1924b894dd3bec5db7c'
Skipping padding
0
                        (MxOb Chunk) 'b'MxOb'' 498 id: 0 7  NoCD_Movie None None
1
                                        (MxOb Chunk) 'b'MxOb'' 170 id: 1 3  CDSpin1_Smk q:\lego\media\movies\CDSpin1.smk
2
                                        (MxOb Chunk) 'b'MxOb'' 183 id: 2 4  Iicx62In_Wave WAV☺ q:\lego\Audio\Offscreen\In\Iicx62In.wav
Audio format might be 11025Hz or 22050Hz, with 16 bits

Exporting wav to c:\temp\NOCD.SI\2_Iicx62In_Wave.wav
Traceback (most recent call last):
  File "C:\Program Files (x86)\LEGO Island\test.py", line 207, in <module>
    extract(args.paths, args.output)
  File "C:\Program Files (x86)\LEGO Island\test.py", line 92, in extract
    w.writeframesraw(x.data[14:])
  File "C:\Python39\lib\wave.py", line 426, in writeframesraw
    self._ensure_header_written(len(data))
  File "C:\Python39\lib\wave.py", line 467, in _ensure_header_written
    self._write_header(datasize)
  File "C:\Python39\lib\wave.py", line 479, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
struct.error: required argument is not an integer
Exception ignored in: <function Wave_write.__del__ at 0x000002D17DC0EF70>
Traceback (most recent call last):
  File "C:\Python39\lib\wave.py", line 326, in __del__
    self.close()
  File "C:\Python39\lib\wave.py", line 444, in close
    self._ensure_header_written(0)
  File "C:\Python39\lib\wave.py", line 467, in _ensure_header_written
    self._write_header(datasize)
  File "C:\Python39\lib\wave.py", line 479, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
struct.error: required argument is not an integer

C:\Program Files (x86)\LEGO Island> 

audio file does not work and is 8.00 Bytes
